export const MOTIVATIONAL_QUOTES = [
  "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor para continuar.",
  "No cuentes los días, haz que los días cuenten.",
  "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.",
  "La mejor manera de predecir el futuro es crearlo.",
  "Si puedes soñarlo, puedes hacerlo.",
  "Tu tiempo es limitado, no lo malgastes viviendo la vida de otro.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "Lo único imposible es aquello que no intentas.",
  "No dejes que lo que no puedes hacer se interponga con lo que puedes hacer.",
  "La disciplina es el puente entre metas y logros.",
  "Los obstáculos son esas cosas espantosas que ves cuando apartas la vista de la meta.",
  "El fracaso es la oportunidad de empezar de nuevo, pero más inteligentemente.",
  "No importa lo lento que vayas, siempre y cuando no te detengas.",
  "Cree en ti mismo y todo será posible.",
  "Haz de cada día tu obra maestra.",
  "La motivación es lo que te hace empezar; el hábito es lo que te mantiene en marcha.",
  "Todo lo que siempre has querido está al otro lado del miedo.",
  "La excelencia no es un acto, sino un hábito.",
  "El éxito suele llegar a quienes están demasiado ocupados para buscarlo.",
  "No busques errores, busca soluciones.",
  "La perseverancia puede cambiar un fracaso en un logro extraordinario.",
  "El coraje no es la ausencia de miedo, sino el triunfo sobre él.",
  "La única manera de hacer un gran trabajo es amar lo que haces.",
  "No mires el reloj; haz lo mismo que él, sigue avanzando.",
  "Empieza donde estás, usa lo que tienes, haz lo que puedes.",
  "La vida es un 10% lo que te pasa y un 90% cómo reaccionas a ello.",
  "El éxito no se trata de lo que logras, sino de lo que inspiras a otros a hacer.",
  "Si quieres ir rápido, ve solo; si quieres llegar lejos, ve acompañado.",
  "Tu actitud, no tu aptitud, determinará tu altitud.",
  "Los desafíos son los que hacen la vida interesante y superarlos es lo que hace la vida significativa.",
  "Nunca es demasiado tarde para ser lo que podrías haber sido.",
  "La paciencia es amarga, pero su fruto es dulce.",
  "El hombre que mueve montañas comienza cargando pequeñas piedras.",
  "El éxito es caer siete veces y levantarse ocho.",
  "Si no luchas por lo que quieres, no te lamentes por lo que pierdes.",
  "El cambio comienza cuando dejas de buscar excusas.",
  "No juzgues cada día por lo que cosechas, sino por las semillas que siembras.",
  "Las oportunidades no aparecen, tú las creas.",
  "Siempre parece imposible hasta que se hace.",
  "Solo una mente positiva puede generar resultados positivos.",
  "El riesgo más grande es no tomar ningún riesgo.",
  "La confianza en uno mismo es el primer secreto del éxito.",
  "No esperes el momento perfecto, toma el momento y hazlo perfecto.",
  "La gloria no consiste en no caer nunca, sino en levantarse cada vez que caemos.",
  "Trabaja duro en silencio, deja que tu éxito sea tu ruido.",
  "Un sueño no se hace realidad por arte de magia; necesita sudor, determinación y trabajo duro.",
  "Si el plan no funciona, cambia el plan, pero nunca la meta.",
  "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.",
  "Haz hoy lo que otros no quieren, haz mañana lo que otros no pueden.",
  "La única diferencia entre el éxito y el fracaso es la capacidad de actuar.",
  "Los grandes logros nacen de grandes sacrificios.",
  "No te detengas hasta que estés orgulloso.",
  "La mejor venganza es el éxito masivo.",
  "El talento gana partidos, pero el trabajo en equipo gana campeonatos.",
  "Tu vida no mejora por casualidad, mejora por el cambio.",
  "Quédate con los que te empujen a ser mejor.",
  "Si no te asusta, no es lo suficientemente grande.",
  "Cada día es una segunda oportunidad.",
  "El momento de ser feliz es ahora.",
  "Deja de esperar que las cosas pasen, sal y haz que pasen.",
  "El único límite es tu mente.",
  "Los ganadores no son aquellos que nunca fracasan, sino los que nunca se rinden.",
  "La felicidad no es algo hecho; viene de tus propias acciones.",
  "Si quieres alcanzar la grandeza, deja de pedir permiso.",
  "Los errores son una prueba de que lo estás intentando.",
  "Una meta sin un plan es solo un deseo.",
  "El conocimiento es poder, pero la acción es lo que da resultados.",
  "Nunca te rindas, las grandes cosas llevan tiempo.",
  "La vida te pondrá obstáculos, pero los límites los pones tú.",
  "Sé la mejor versión de ti mismo.",
  "El éxito es la capacidad de ir de fracaso en fracaso sin perder el entusiasmo.",
  "Todo lo que puedes imaginar es real.",
  "No te compares con nadie, compárate con quien eras ayer.",
  "Si no puedes volar, corre; si no puedes correr, camina; si no puedes caminar, gatea.",
  "La mayor aventura que puedes tener es vivir la vida de tus sueños.",
  "No dejes que el miedo a perder sea mayor que la emoción de ganar.",
  "El éxito no es para los que creen que pueden, sino para los que saben que pueden.",
  "Eres más fuerte de lo que crees.",
  "Cada cicatriz es una lección aprendida.",
  "No cuentes los problemas, cuenta las bendiciones.",
  "El éxito consiste en obtener lo que quieres; la felicidad en querer lo que obtienes.",
  "El secreto para salir adelante es comenzar.",
  "No intentes ser una persona de éxito, sino una persona de valor.",
  "Lo que haces hoy puede mejorar todos tus mañanas.",
  "Si no estás cometiendo errores, no estás innovando lo suficiente.",
  "La vida es demasiado corta para ser pequeña.",
  "Tu energía es tu moneda más valiosa.",
  "Quien tiene un porqué para vivir, puede soportar casi cualquier cómo.",
  "El pesimista ve dificultad en toda oportunidad; el optimista ve oportunidad en toda dificultad.",
  "Hazlo, y si te da miedo, hazlo con miedo.",
  "No se trata de si te derriban, se trata de si te levantas.",
  "Tus sueños no tienen fecha de caducidad.",
  "La consistencia es más importante que la intensidad.",
  "Si no te gusta dónde estás, muévete, no eres un árbol.",
  "El éxito comienza por hacer lo necesario ahora.",
  "Los días difíciles son los que te construyen.",
  "El 80% del éxito se basa simplemente en insistir.",
  "Da siempre lo mejor de ti, y lo mejor vendrá.",
  "Para ser el mejor, tienes que ser capaz de manejar lo peor.",
  "Sé el cambio que quieres ver en el mundo.",
  "No digas \"es imposible\", di \"no lo he hecho todavía\".",
  "La mente que se abre a una nueva idea nunca volverá a su tamaño original.",
  "Tu destino está en tus manos.",
  "El éxito es una decisión, no un regalo.",
  "No dejes que la opinión de los demás sea tu realidad.",
  "Enfócate en el progreso, no en la perfección.",
  "Los líderes no crean seguidores, crean más líderes.",
  "La vida se encoge o se expande en proporción a tu coraje.",
  "No eres lo que logras, eres lo que superas.",
  "Ama lo que haces y nunca trabajarás un solo día de tu vida.",
  "El que deja de aprender, deja de crecer.",
  "Las tormentas no duran para siempre.",
  "No te rindas justo antes de que ocurra el milagro.",
  "La disciplina es hacer lo que hay que hacer, incluso cuando no quieres.",
  "Los sueños se cumplen cuando despiertas y trabajas por ellos.",
  "No busques aprobación, busca impacto.",
  "La gratitud es la memoria del corazón.",
  "El único modo de descubrir los límites de lo posible es yendo más allá de lo imposible.",
  "Aprende del ayer, vive para hoy, espera por el mañana.",
  "Tu potencial es infinito.",
  "Una gema no puede ser pulida sin fricción.",
  "El éxito no se mide por la posición alcanzada, sino por los obstáculos superados.",
  "Hazlo ahora, a veces \"luego\" se convierte en \"nunca\".",
  "Si el camino es difícil, es porque vas por la dirección correcta.",
  "Rodéate de personas que tengan metas, no solo opiniones.",
  "Lo que no te mata, te hace más fuerte.",
  "El éxito es un viaje, no un destino.",
  "Mantén tus ojos en las estrellas y tus pies en el suelo.",
  "No hay nada imposible para aquel que lo intenta.",
  "Sé tan bueno que no puedan ignorarte.",
  "El trabajo duro vence al talento cuando el talento no trabaja duro.",
  "Si quieres algo que nunca has tenido, debes estar dispuesto a hacer algo que nunca has hecho.",
  "El pasado es un lugar de referencia, no un lugar de residencia.",
  "La motivación te ayuda a empezar, el compromiso te ayuda a terminar.",
  "Cree que puedes y ya estarás a mitad de camino.",
  "No importa cuántas veces falles, solo tienes que tener razón una vez.",
  "La duda mata más sueños que el fracaso.",
  "Eres el arquitecto de tu propio destino.",
  "Haz lo que puedas con lo que tengas, estés donde estés.",
  "La perseverancia es el trabajo duro que haces después de cansarte del trabajo duro que ya hiciste.",
  "No hay ascensor al éxito, tienes que tomar las escaleras.",
  "Tus acciones hablan más fuerte que tus palabras.",
  "El éxito es la mejor respuesta a tus críticos.",
  "No esperes a que las condiciones sean perfectas para empezar.",
  "La vida no se trata de encontrarse a uno mismo, sino de crearse a uno mismo.",
  "Tu única competencia es la persona que ves en el espejo.",
  "Si quieres resultados diferentes, no hagas siempre lo mismo.",
  "La victoria es más dulce cuando has conocido la derrota.",
  "Un viaje de mil millas comienza con un solo paso.",
  "El éxito no llega a ti, tú vas hacia él.",
  "Sé el tipo de persona que deja huella, no cicatrices.",
  "Tu voluntad es tu fuerza más poderosa.",
  "Nunca subestimes el poder de un pequeño acto de bondad.",
  "El aprendizaje es un tesoro que seguirá a su dueño a todas partes.",
  "Las grandes mentes discuten ideas; las mentes promedio discuten eventos; las mentes pequeñas discuten personas.",
  "No dejes que ayer ocupe demasiado del día de hoy.",
  "La sabiduría es saber qué hacer a continuación; la virtud es hacerlo.",
  "Si no construyes tu sueño, alguien te contratará para que ayudes a construir el suyo.",
  "La mejor inversión que puedes hacer es en ti mismo.",
  "Mantente hambriento, mantente audaz.",
  "La simplicidad es la máxima sofisticación.",
  "El valor de una idea radica en el uso de la misma.",
  "El fracaso es solo la oportunidad de comenzar de nuevo de forma más inteligente.",
  "Nada grande se logró jamás sin entusiasmo.",
  "El genio es un 1% de inspiración y un 99% de transpiración.",
  "La calidad de tu vida depende de la calidad de tus pensamientos.",
  "Si te caíste ayer, levántate hoy.",
  "El éxito no es la clave de la felicidad; la felicidad es la clave del éxito.",
  "Los retos son regalos que nos obligan a buscar un nuevo centro de gravedad.",
  "Solo aquellos que se arriesgan a ir demasiado lejos pueden descubrir hasta dónde se puede llegar.",
  "Tu tiempo es ahora.",
  "No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas.",
  "El que no arriesga, no gana.",
  "Hazlo por ti, no por los demás.",
  "Cada día trae nuevas opciones.",
  "No juzgues tus éxitos por lo que has logrado, sino por lo que ha tenido que renunciar para obtenerlo.",
  "El éxito no es para los que persisten, es para los que persisten.",
  "La imaginación es el principio de la creación.",
  "No cuentes tus sueños, muéstralos.",
  "La resiliencia es tu capacidad para florecer en el desierto.",
  "Lo que pienses de ti mismo es mucho más importante que lo que otros piensen de ti.",
  "Sé un guerrero, no un angustiado.",
  "La vida comienza al final de tu zona de confort.",
  "Tu pasión es tu propósito.",
  "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.",
  "Los sueños no funcionan a menos que tú lo hagas.",
  "El coraje es como un músculo: lo fortalecemos al usarlo.",
  "Tu enfoque determina tu realidad.",
  "No permitas que el ruido de las opiniones ajenas silencie tu voz interior.",
  "La gratitud convierte lo que tenemos en suficiente.",
  "El éxito es vivir la vida a tu manera.",
  "Sé luz en la oscuridad.",
  "Lo que buscas te está buscando a ti.",
  "El hombre más rico no es el que tiene más, sino el que necesita menos.",
  "La bondad es el lenguaje que el sordo puede oír y el ciego puede ver.",
  "No dejes que el mundo cambie tu sonrisa, deja que tu sonrisa cambie el mundo.",
  "El ayer es historia, el mañana es un misterio, el hoy es un regalo.",
  "Eres suficiente tal y como eres.",
  "Todo pasa por algo.",
  "Lo mejor está por venir."
];
